<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="unittest.loader._FailedTest-20220415122002" tests="1" file="unittest/loader.py" time="0.024" timestamp="2022-04-15T12:20:05" failures="0" errors="1" skipped="0">
	<testcase classname="unittest.loader._FailedTest" name="calculater_tests" time="0.024" timestamp="2022-04-15T12:20:05">
		<error type="ImportError" message="Failed to import test module: calculater_tests
Traceback (most recent call last):
  File &quot;D:\Programs\Python\Python310\lib\unittest\loader.py&quot;, line 154, in loadTestsFromName
    module = __import__(module_name)
  File &quot;d:\projects\dot503a2_test\src\unittest\python\calculater_tests.py&quot;, line 2, in &lt;module&gt;
    from src.main.python.Calculator import Calculator
ModuleNotFoundError: No module named 'src'
"><![CDATA[Traceback (most recent call last):
  File "D:\Programs\Python\Python310\lib\unittest\case.py", line 59, in testPartExecutor
    yield
  File "D:\Programs\Python\Python310\lib\unittest\case.py", line 591, in run
    self._callTestMethod(testMethod)
  File "D:\Programs\Python\Python310\lib\unittest\case.py", line 549, in _callTestMethod
    method()
  File "D:\Programs\Python\Python310\lib\unittest\loader.py", line 34, in testFailure
    raise self._exception
ImportError: Failed to import test module: calculater_tests
Traceback (most recent call last):
  File "D:\Programs\Python\Python310\lib\unittest\loader.py", line 154, in loadTestsFromName
    module = __import__(module_name)
  File "d:\projects\dot503a2_test\src\unittest\python\calculater_tests.py", line 2, in <module>
    from src.main.python.Calculator import Calculator
ModuleNotFoundError: No module named 'src'

]]></error>
	</testcase>
</testsuite>
